import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
import NextAuthProvider from "@/provider/NextAuthProvider";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Smart Med Appointments",
  description: "Generated by Team 5",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* <TanstackProvider> */}
            <Navbar />
            <div className="min-h-screen">

            {children}
            </div>
            <Toaster />
            <Footer></Footer>
            {/* <ReactQueryDevtools initialIsOpen={false} /> */}
          {/* </TanstackProvider> */}
        </body>
      </NextAuthProvider>
    </html>
  );
}
