import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
 Abu-Sayed
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
development

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Smart Med Appointments",
  description: "Generated by Team 5",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
